import { GameOneQuestion, GameTwoQuestion, CoachQuestion, MentalMathItem, FinalRoleTask } from './types';

export const GAME_ONE_QUESTIONS: GameOneQuestion[] = [
  // Ronda 1 — Decisiones rápidas
  {
    id: 1,
    round: 1,
    roundTitleEs: 'Ronda 1 — Decisiones rápidas',
    roundTitleHy: 'Փուլ 1 — Արագ որոշումներ',
    titleEs: 'El último minuto',
    titleHy: 'Վերջին րոպեն',
    situationEs: 'Queda un minuto para terminar el partido. Tu equipo pierde 2-1. Recibes el balón cerca de la portería.',
    situationHy: 'Խաղի ավարտին մնացել է մեկ րոպե։ Քո թիմը պարտվում է 2-1 հաշվով։ Դու գնդակ ես ստանում դարպասի մոտ։',
    questionEs: '¿Qué harás?',
    questionHy: 'Ի՞նչ կանես։',
    options: [
      { key: 'A', textEs: 'Intentaré marcar un gol.', textHy: 'Կփորձեմ գոլ խփել։' },
      { key: 'B', textEs: 'Me iré a dormir.', textHy: 'Քնելու կգնամ։' },
      { key: 'C', textEs: 'Apagaré la televisión.', textHy: 'Կանջատեմ հեռուստացույցը։' },
      { key: 'D', textEs: 'Llamaré a mi profesor.', textHy: 'Կզանգահարեմ ուսուցչիս։' },
    ],
    correctAnswer: 'A',
    verbInFocus: 'Intentaré (intentar) / Harás (hacer)',
    explanationHy: '«Intentaré marcar un gol» նշանակում է «Կփորձեմ գոլ խփել»։ Խաղի վերջին րոպեին միակ տրամաբանական քայլն է փորձել հավասարեցնել հաշիվը։',
  },
  {
    id: 2,
    round: 1,
    roundTitleEs: 'Ronda 1 — Decisiones rápidas',
    roundTitleHy: 'Փուլ 1 — Արագ որոշումներ',
    titleEs: 'El amigo nervioso',
    titleHy: 'Հուզված ընկերը',
    situationEs: 'Tu mejor amigo jugará su primer partido importante. Está muy nervioso.',
    situationHy: 'Քո լավագույն ընկերն առաջին կարևոր խաղն է անցկացնելու։ Նա շատ հուզված է։',
    questionEs: '¿Qué le dirás?',
    questionHy: 'Ի՞նչ կասես նրան։',
    options: [
      { key: 'A', textEs: 'Nunca jugarás bien.', textHy: 'Երբեք լավ չես խաղա։' },
      { key: 'B', textEs: '¡Lo harás muy bien!', textHy: 'Դու շատ լավ կխաղաս / կանես դա։' },
      { key: 'C', textEs: 'No tendrás amigos.', textHy: 'Ընկերներ չես ունենա։' },
      { key: 'D', textEs: 'Llegarás tarde a clase.', textHy: 'Դասից կուշանաս։' },
    ],
    correctAnswer: 'B',
    verbInFocus: 'Harás (hacer) / Dirás (decir)',
    explanationHy: '«¡Lo harás muy bien!» — «Դու հիանալի կանես դա / շատ լավ կխաղաս»։ Հուզված ընկերոջը քաջալերելու լավագույն խոսքն է։',
  },
  {
    id: 3,
    round: 1,
    roundTitleEs: 'Ronda 1 — Decisiones rápidas',
    roundTitleHy: 'Փուլ 1 — Արագ որոշումներ',
    titleEs: 'La lluvia inesperada',
    titleHy: 'Անսպասելի անձրև',
    situationEs: 'Mañana tendrás un entrenamiento al aire libre, pero lloverá mucho.',
    situationHy: 'Վաղը բացօթյա մարզում ունես, բայց ուժեղ անձրև կգա։',
    questionEs: '¿Qué harás?',
    questionHy: 'Ի՞նչ կանես։',
    options: [
      { key: 'A', textEs: 'Comprarás un helado.', textHy: 'Պաղպաղակ կգնես։' },
      { key: 'B', textEs: 'Visitarás un museo.', textHy: 'Թանգարան կայցելես։' },
      { key: 'C', textEs: 'Preguntarás si el entrenamiento se hará en otro lugar.', textHy: 'Կհարցնես, արդյոք մարզումը կանցկացվի այլ վայրում։' },
      { key: 'D', textEs: 'Irás a la playa a nadar.', textHy: 'Ծովափ կգնաս լողալու։' },
    ],
    correctAnswer: 'C',
    verbInFocus: 'Preguntarás (preguntar) / Se hará (hacerse)',
    explanationHy: '«Preguntarás si el entrenamiento se hará en otro lugar» — «Կհարցնես, արդյոք մարզումը կկայանա այլ վայրում»։ Բացօթյա անձրևի դեպքում ստուգում են փակ դահլիճը։',
  },
  {
    id: 4,
    round: 1,
    roundTitleEs: 'Ronda 1 — Decisiones rápidas',
    roundTitleHy: 'Փուլ 1 — Արագ որոշումներ',
    titleEs: 'La entrada perdida',
    titleHy: 'Կորած տոմս',
    situationEs: 'Estás delante del estadio, pero no encuentras tu entrada. El partido empezará dentro de veinte minutos.',
    situationHy: 'Դու մարզադաշտի առջև ես, բայց չես գտնում տոմսդ։ Խաղը կսկսվի քսան րոպեից։',
    questionEs: '¿Qué harás?',
    questionHy: 'Ի՞նչ կանես։',
    options: [
      { key: 'A', textEs: 'Me compraré unos zapatos.', textHy: 'Կոշիկներ կգնեմ։' },
      { key: 'B', textEs: 'Prepararé la cena.', textHy: 'Ընթրիք կպատրաստեմ։' },
      { key: 'C', textEs: 'Jugaré al tenis.', textHy: 'Թենիս կխաղամ։' },
      { key: 'D', textEs: 'Buscaré la entrada en mi móvil y en mis bolsillos.', textHy: 'Տոմսը կփնտրեմ հեռախոսիս մեջ և գրպաններումս։' },
    ],
    correctAnswer: 'D',
    verbInFocus: 'Buscaré (buscar) / Empezará (empezar)',
    explanationHy: '«Buscaré la entrada en mi móvil y en mis bolsillos» — «Տոմսը կփնտրեմ հեռախոսումս և գրպաններումս»։',
  },
  {
    id: 5,
    round: 1,
    roundTitleEs: 'Ronda 1 — Decisiones rápidas',
    roundTitleHy: 'Փուլ 1 — Արագ որոշումներ',
    titleEs: 'El capitán lesionado',
    titleHy: 'Վնասվածք ստացած ավագը',
    situationEs: 'El capitán de tu equipo no podrá jugar mañana. El entrenador te elige como nuevo capitán.',
    situationHy: 'Քո թիմի ավագը վաղը չի կարող խաղալ։ Մարզիչը քեզ է ընտրում որպես նոր ավագ։',
    questionEs: '¿Qué harás?',
    questionHy: 'Ի՞նչ կանես։',
    options: [
      { key: 'A', textEs: 'Animaré a mis compañeros.', textHy: 'Կոգեշնչեմ թիմակիցներիս։' },
      { key: 'B', textEs: 'Me quedaré en la cama.', textHy: 'Անկողնում կմնամ։' },
      { key: 'C', textEs: 'Me olvidaré del partido.', textHy: 'Կմոռանամ խաղի մասին։' },
      { key: 'D', textEs: 'Cambiaré de deporte inmediatamente.', textHy: 'Անմիջապես կփոխեմ սպորտաձևը։' },
    ],
    correctAnswer: 'A',
    verbInFocus: 'Animaré (animar) / Podrá (poder)',
    explanationHy: '«Animaré a mis compañeros» — «Կոգեշնչեմ թիմակիցներիս»։ Որպես ավագ՝ պետք է ոգևորել ու առաջնորդել թիմին։',
  },

  // Ronda 2 — ¿Qué decisión tomarás?
  {
    id: 6,
    round: 2,
    roundTitleEs: 'Ronda 2 — ¿Qué decisión tomarás?',
    roundTitleHy: 'Փուլ 2 — Ի՞նչ որոշում կկայացնես',
    titleEs: 'Dos invitaciones',
    titleHy: 'Երկու հրավեր',
    situationEs: 'El sábado tendrás dos invitaciones: una para ver un partido de fútbol y otra para ir al cumpleaños de tu mejor amigo. Las dos actividades serán a la misma hora.',
    situationHy: 'Շաբաթ օրը երկու հրավեր կունենաս՝ ֆուտբոլային խաղ դիտելու և լավագույն ընկերոջդ ծննդյան օրը մասնակցելու։ Երկուսն էլ նույն ժամին կլինեն։',
    questionEs: '¿Qué harás?',
    questionHy: 'Ի՞նչ կանես։',
    options: [
      { key: 'A', textEs: 'Dormiré todo el fin de semana.', textHy: 'Ողջ հանգստյան օրերին կքնեմ։' },
      { key: 'B', textEs: 'Hablaré con mi amigo y buscaré una solución.', textHy: 'Կխոսեմ ընկերոջս հետ և լուծում կգտնեմ։' },
      { key: 'C', textEs: 'No volveré a hablar con nadie.', textHy: 'Այլևս ոչ ոքի հետ չեմ խոսի։' },
      { key: 'D', textEs: 'Venderé mi bicicleta.', textHy: 'Հեծանիվս կվաճառեմ։' },
    ],
    correctAnswer: 'B',
    verbInFocus: 'Hablaré (hablar) / Buscaré (buscar) / Serán (ser)',
    explanationHy: '«Hablaré con mi amigo y buscaré una solución» — Ընկերոջ հետ խոսելն ու լուծում գտնելը ամենահասուն որոշումն է։',
  },
  {
    id: 7,
    round: 2,
    roundTitleEs: 'Ronda 2 — ¿Qué decisión tomarás?',
    roundTitleHy: 'Փուլ 2 — Ի՞նչ որոշում կկայացնես',
    titleEs: 'Un regalo sorpresa',
    titleHy: 'Անակնկալ նվեր',
    situationEs: 'Tu familia quiere regalarte algo por tu cumpleaños. Puedes elegir entre una camiseta firmada por tu futbolista favorito y una entrada para un partido importante.',
    situationHy: 'Ընտանիքդ ցանկանում է քեզ ծննդյան նվեր մատուցել։ Կարող ես ընտրել սիրելի ֆուտբոլիստիդ ստորագրությամբ մարզաշապիկ կամ կարևոր խաղի տոմս։',
    questionEs: '¿Qué elegirás?',
    questionHy: 'Ի՞նչ կընտրես։',
    options: [
      { key: 'A', textEs: 'Compraré tomates.', textHy: 'Լոլիկ կգնեմ։' },
      { key: 'B', textEs: 'No iré al colegio nunca más.', textHy: 'Այլևս երբեք դպրոց չեմ գնա։' },
      { key: 'C', textEs: 'Elegiré la entrada porque viviré una experiencia inolvidable.', textHy: 'Կընտրեմ տոմսը, քանի որ անմոռանալի տպավորություն կստանամ։' },
      { key: 'D', textEs: 'Cerraré todas las ventanas.', textHy: 'Բոլոր պատուհանները կփակեմ։' },
    ],
    correctAnswer: 'C',
    verbInFocus: 'Elegiré (elegir) / Viviré (vivir)',
    explanationHy: '«Elegiré la entrada porque viviré una experiencia inolvidable» — Անմոռանալի փորձառություն ապրելու համար կընտրի տոմսը։',
  },
  {
    id: 8,
    round: 2,
    roundTitleEs: 'Ronda 2 — ¿Qué decisión tomarás?',
    roundTitleHy: 'Փուլ 2 — Ի՞նչ որոշում կկայացնես',
    titleEs: 'La decisión del árbitro',
    titleHy: 'Մրցավարի որոշումը',
    situationEs: 'El árbitro señalará un penalti contra tu equipo, pero tú pensarás que no será justo.',
    situationHy: 'Մրցավարը քո թիմի դեմ տուգանային հարված կնշանակի, բայց դու կհամարես, որ որոշումն անարդար է։',
    questionEs: '¿Cómo reaccionarás?',
    questionHy: 'Ինչպե՞ս կարձագանքես։',
    options: [
      { key: 'A', textEs: 'Romperé todo el estadio.', textHy: 'Կջարդեմ ամբողջ մարզադաշտը։' },
      { key: 'B', textEs: 'Me iré de vacaciones.', textHy: 'Արձակուրդ կգնամ։' },
      { key: 'C', textEs: 'Dejaré de estudiar matemáticas.', textHy: 'Կդադարեմ մաթեմատիկա սովորել։' },
      { key: 'D', textEs: 'Expresaré mi desacuerdo con respeto.', textHy: 'Հարգանքով կարտահայտեմ իմ անհամաձայնությունը։' },
    ],
    correctAnswer: 'D',
    verbInFocus: 'Expresaré (expresar) / Señalará (señalar)',
    explanationHy: '«Expresaré mi desacuerdo con respeto» — Սպորտսմենը միշտ հարգանքով է հայտնում իր անհամաձայնությունը։',
  },
  {
    id: 9,
    round: 2,
    roundTitleEs: 'Ronda 2 — ¿Qué decisión tomarás?',
    roundTitleHy: 'Փուլ 2 — Ի՞նչ որոշում կկայացնես',
    titleEs: 'El entrenador te observa',
    titleHy: 'Մարզիչը հետևում է քեզ',
    situationEs: 'Un entrenador famoso visitará tu escuela y observará cómo juegas.',
    situationHy: 'Հայտնի մարզիչը կայցելի քո դպրոց և կհետևի, թե ինչպես ես խաղում։',
    questionEs: '¿Qué harás para causar una buena impresión?',
    questionHy: 'Ի՞նչ կանես լավ տպավորություն թողնելու համար։',
    options: [
      { key: 'A', textEs: 'Daré lo mejor de mí y ayudaré al equipo.', textHy: 'Կտամ իմ առավելագույնը և կօգնեմ թիմին։' },
      { key: 'B', textEs: 'Me esconderé en el vestuario.', textHy: 'Կթաքնվեմ հանդերձարանում։' },
      { key: 'C', textEs: 'Olvidaré mis zapatillas a propósito.', textHy: 'Դիտմամբ կմոռանամ մարզակոշիկներս։' },
      { key: 'D', textEs: 'Me quedaré mirando el móvil.', textHy: 'Կմնամ հեռախոսին նայելով։' },
    ],
    correctAnswer: 'A',
    verbInFocus: 'Daré (dar) / Ayudaré (ayudar) / Visitará (visitar)',
    explanationHy: '«Daré lo mejor de mí y ayudaré al equipo» — «Կտամ իմ լավագույնը և կօգնեմ թիմին»։',
  },
  {
    id: 10,
    round: 2,
    roundTitleEs: 'Ronda 2 — ¿Qué decisión tomarás?',
    roundTitleHy: 'Փուլ 2 — Ի՞նչ որոշում կկայացնես',
    titleEs: 'El partido contra tus amigos',
    titleHy: 'Խաղ ընկերներիդ դեմ',
    situationEs: 'El próximo fin de semana jugarás contra un equipo en el que estarán dos de tus mejores amigos.',
    situationHy: 'Հաջորդ հանգստյան օրերին կխաղաս մի թիմի դեմ, որտեղ կլինեն երկու լավագույն ընկերներդ։',
    questionEs: '¿Cómo te comportarás?',
    questionHy: 'Ինչպե՞ս կվարվես։',
    options: [
      { key: 'A', textEs: 'No respetaré las reglas.', textHy: 'Չեմ հարգի կանոնները։' },
      { key: 'B', textEs: 'Competiré con ganas y después los felicitaré.', textHy: 'Կմրցեմ ոգևորությամբ և հետո կշնորհավորեմ նրանց։' },
      { key: 'C', textEs: 'Discutiré durante todo el partido.', textHy: 'Կվիճեմ ամբողջ խաղի ընթացքում։' },
      { key: 'D', textEs: 'Nunca volveré a jugar.', textHy: 'Երբեք նորից չեմ խաղա։' },
    ],
    correctAnswer: 'B',
    verbInFocus: 'Competiré (competir) / Felicitaré (felicitar)',
    explanationHy: '«Competiré con ganas y después los felicitaré» — Սպորտային ոգին պահանջում է եռանդով մրցել և խաղից հետո ընկերաբար շնորհավորել։',
  },

  // Ronda 3 — Imagina el futuro
  {
    id: 11,
    round: 3,
    roundTitleEs: 'Ronda 3 — Imagina el futuro',
    roundTitleHy: 'Փուլ 3 — Պատկերացրու ապագան',
    titleEs: 'Un viaje a Madrid',
    titleHy: 'Ճանապարհորդություն Մադրիդ',
    situationEs: 'Viajarás a Madrid y tendrás la oportunidad de visitar el estadio Santiago Bernabéu.',
    situationHy: 'Կճանապարհորդես Մադրիդ և հնարավորություն կունենաս այցելել «Սանտիագո Բեռնաբեու» մարզադաշտ։',
    questionEs: '¿Qué harás primero?',
    questionHy: 'Նախ ի՞նչ կանես։',
    options: [
      { key: 'A', textEs: 'Iré a otro país inmediatamente.', textHy: 'Անմիջապես այլ երկիր կգնամ։' },
      { key: 'B', textEs: 'Cocinaré una sopa.', textHy: 'Ապուր կեփեմ։' },
      { key: 'C', textEs: 'Haré muchas fotografías del estadio.', textHy: 'Մարզադաշտի բազմաթիվ լուսանկարներ կանեմ։' },
      { key: 'D', textEs: 'Me quedaré en el aeropuerto.', textHy: 'Օդանավակայանում կմնամ։' },
    ],
    correctAnswer: 'C',
    verbInFocus: 'Haré (hacer: anegativo/irregular) / Viajarás (viajar)',
    explanationHy: '«Haré muchas fotografías del estadio» — Բեռնաբեուում առաջին բանը մարզադաշտը լուսանկարելն է։',
  },
  {
    id: 12,
    round: 3,
    roundTitleEs: 'Ronda 3 — Imagina el futuro',
    roundTitleHy: 'Փուլ 3 — Պատկերացրու ապագան',
    titleEs: 'Una conversación con Cristiano Ronaldo',
    titleHy: 'Զրույց Ռոնալդուի հետ',
    situationEs: 'Imagina que mañana conocerás a Cristiano Ronaldo y podrás hacerle una sola pregunta.',
    situationHy: 'Պատկերացրու՝ վաղը կհանդիպես Կրիշտիանու Ռոնալդուին և միայն մեկ հարց տալու հնարավորություն կունենաս։',
    questionEs: '¿Qué le preguntarás?',
    questionHy: 'Ի՞նչ կհարցնես։',
    options: [
      { key: 'A', textEs: '¿Dónde comprarás verduras mañana?', textHy: 'Վաղը որտե՞ղ կգնես բանջարեղեն։' },
      { key: 'B', textEs: '¿De qué color pintarás tu cocina?', textHy: 'Ի՞նչ գույնով կներկես խոհանոցդ։' },
      { key: 'C', textEs: '¿Cuándo limpiarás tu habitación?', textHy: 'Ե՞րբ կմաքրես սենյակդ։' },
      { key: 'D', textEs: '¿Qué consejo me darás para mejorar como futbolista?', textHy: 'Ի՞նչ խորհուրդ կտաս ինձ՝ որպես ֆուտբոլիստ կատարելագործվելու համար։' },
    ],
    correctAnswer: 'D',
    verbInFocus: 'Darás (dar) / Preguntarás (preguntar)',
    explanationHy: '«¿Qué consejo me darás para mejorar como futbolista?» — Աշխարհի լավագույն ֆուտբոլիստներից մեկին տրվող ամենակարևոր հարցը։',
  },
  {
    id: 13,
    round: 3,
    roundTitleEs: 'Ronda 3 — Imagina el futuro',
    roundTitleHy: 'Փուլ 3 — Պատկերացրու ապագան',
    titleEs: 'El Mundial del futuro',
    titleHy: 'Ապագայի աշխարհի առաջնությունը',
    situationEs: 'Imagina que dentro de diez años podrás viajar a cualquier país para ver un Mundial.',
    situationHy: 'Պատկերացրու՝ տասը տարի հետո աշխարհի առաջնությունը դիտելու համար կկարողանաս մեկնել ցանկացած երկիր։',
    questionEs: '¿A qué país irás?',
    questionHy: 'Ո՞ր երկիր կմեկնես։',
    options: [
      { key: 'A', textEs: 'Iré al país donde se celebre el Mundial.', textHy: 'Կգնամ այն երկիր, որտեղ կանցկացվի Աշխարհի առաջնությունը։' },
      { key: 'B', textEs: 'Estuve en casa ayer.', textHy: 'Երեկ տանն էի։ (Անցյալ ժամանակ)' },
      { key: 'C', textEs: 'Estoy haciendo los deberes.', textHy: 'Տնայիններս եմ անում։ (Ներկա ժամանակ)' },
      { key: 'D', textEs: 'Nunca he viajado en avión.', textHy: 'Երբեք ինքնաթիռով չեմ ճամփորդել։' },
    ],
    correctAnswer: 'A',
    verbInFocus: 'Iré (ir) / Podrás (poder)',
    explanationHy: '«Iré al país donde se celebre el Mundial» — Ճիշտ Futuro Simple ժամանակով պատասխանն է։',
  },
  {
    id: 14,
    round: 3,
    roundTitleEs: 'Ronda 3 — Imagina el futuro',
    roundTitleHy: 'Փուլ 3 — Պատկերացրու ապագան',
    titleEs: 'Una nueva tecnología',
    titleHy: 'Նոր տեխնոլոգիա',
    situationEs: 'En el futuro, los entrenadores utilizarán robots para analizar los movimientos de los jugadores.',
    situationHy: 'Ապագայում մարզիչները ռոբոտներ կօգտագործեն ֆուտբոլիստների շարժումները վերլուծելու համար։',
    questionEs: '¿Para qué servirán?',
    questionHy: 'Ինչի՞ համար դրանք օգտակար կլինեն։',
    options: [
      { key: 'A', textEs: 'Para preparar pasteles.', textHy: 'Թխվածք պատրաստելու համար։' },
      { key: 'B', textEs: 'Ayudarán a mejorar los entrenamientos.', textHy: 'Կօգնեն բարելավել մարզումները։' },
      { key: 'C', textEs: 'Para vender entradas de cine.', textHy: 'Կինոյի տոմսեր վաճառելու համար։' },
      { key: 'D', textEs: 'Para cambiar el tiempo.', textHy: 'Եղանակը փոխելու համար։' },
    ],
    correctAnswer: 'B',
    verbInFocus: 'Ayudarán (ayudar) / Utilizarán (utilizar) / Servirán (servir)',
    explanationHy: '«Ayudarán a mejorar los entrenamientos» — Ռոբոտները կօգնեն մարզիչներին ավելի որակյալ դարձնել մարզումները։',
  },
  {
    id: 15,
    round: 3,
    roundTitleEs: 'Ronda 3 — Imagina el futuro',
    roundTitleHy: 'Փուլ 3 — Պատկերացրու ապագան',
    titleEs: 'Tu propio estadio',
    titleHy: 'Քո սեփական մարզադաշտը',
    situationEs: 'Imagina que serás el dueño de un estadio de fútbol. Podrás cambiar tres cosas.',
    situationHy: 'Պատկերացրու՝ դու ֆուտբոլային մարզադաշտի սեփականատեր կլինես։ Կարող ես երեք բան փոխել։',
    questionEs: '¿Qué construirás?',
    questionHy: 'Ի՞նչ կկառուցես։',
    options: [
      { key: 'A', textEs: 'Un supermercado en el campo.', textHy: 'Սուպերմարկետ խաղադաշտում։' },
      { key: 'B', textEs: 'Una fábrica de zapatos.', textHy: 'Կոշիկի գործարան։' },
      { key: 'C', textEs: 'Una zona moderna de entrenamiento y espacios cómodos para los aficionados.', textHy: 'Ժամանակակից մարզագոտի և հարմարավետ վայրեր երկրպագուների համար։' },
      { key: 'D', textEs: 'Una escuela de cocina en la portería.', textHy: 'Խոհարարական դպրոց դարպասում։' },
    ],
    correctAnswer: 'C',
    verbInFocus: 'Construirás (construir) / Serás (ser)',
    explanationHy: '«Una zona moderna de entrenamiento y espacios cómodos para los aficionados» — Մարզադաշտի տիրոջ լավագույն ներդրումը։',
  },

  // Ronda 4 — Situaciones inesperadas
  {
    id: 16,
    round: 4,
    roundTitleEs: 'Ronda 4 — Situaciones inesperadas',
    roundTitleHy: 'Փուլ 4 — Անսպասելի իրավիճակներ',
    titleEs: 'El balón desaparecido',
    titleHy: 'Անհետացած գնդակ',
    situationEs: 'Durante un entrenamiento, el balón cae detrás de una puerta cerrada. Nadie tiene la llave.',
    situationHy: 'Մարզման ժամանակ գնդակն ընկնում է փակ դռան հետևը։ Ոչ ոք բանալի չունի։',
    questionEs: '¿Cómo solucionaréis el problema?',
    questionHy: 'Ինչպե՞ս կլուծեք խնդիրը։',
    options: [
      { key: 'A', textEs: 'Romperemos la puerta.', textHy: 'Կկոտրենք դուռը։' },
      { key: 'B', textEs: 'Cancelaremos todos los partidos del año.', textHy: 'Կչեղարկենք տարվա բոլոր խաղերը։' },
      { key: 'C', textEs: 'Nos iremos a otro país.', textHy: 'Այլ երկիր կմեկնենք։' },
      { key: 'D', textEs: 'Buscaremos al responsable y pediremos otra pelota.', textHy: 'Կփնտրենք պատասխանատուին և մեկ այլ գնդակ կխնդրենք։' },
    ],
    correctAnswer: 'D',
    verbInFocus: 'Buscaremos (buscar) / Pediremos (pedir) / Solucionaréis (solucionar)',
    explanationHy: '«Buscaremos al responsable y pediremos otra pelota» — Ճիշտ լուծումը մարզադաշտի պատասխանատուին գտնելն է։',
  },
  {
    id: 17,
    round: 4,
    roundTitleEs: 'Ronda 4 — Situaciones inesperadas',
    roundTitleHy: 'Փուլ 4 — Անսպասելի իրավիճակներ',
    titleEs: 'Una promesa difícil',
    titleHy: 'Դժվար խոստում',
    situationEs: 'Prometes a tu entrenador que mejorarás tu forma física en dos meses.',
    situationHy: 'Մարզչիդ խոստանում ես, որ երկու ամսում կբարելավես ֆիզիկական պատրաստվածությունդ։',
    questionEs: '¿Qué plan seguirás?',
    questionHy: 'Ի՞նչ ծրագրի կհետևես։',
    options: [
      { key: 'A', textEs: 'Entrenaré regularmente, descansaré y comeré bien.', textHy: 'Կանոնավոր կմարզվեմ, կհանգստանամ և լավ կսնվեմ։' },
      { key: 'B', textEs: 'Comeré dulces durante cada entrenamiento.', textHy: 'Քաղցրավենիք կուտեմ յուրաքանչյուր մարզման ժամանակ։' },
      { key: 'C', textEs: 'No dormiré nunca.', textHy: 'Երբեք չեմ քնի։' },
      { key: 'D', textEs: 'Dejaré de practicar.', textHy: 'Կդադարեմ պարապել։' },
    ],
    correctAnswer: 'A',
    verbInFocus: 'Entrenaré (entrenar) / Descansaré (descansar) / Comeré (comer)',
    explanationHy: '«Entrenaré regularmente, descansaré y comeré bien» — Ֆիզիկական մարզավիճակ ձեռք բերելու հիմնասյուները։',
  },
  {
    id: 18,
    round: 4,
    roundTitleEs: 'Ronda 4 — Situaciones inesperadas',
    roundTitleHy: 'Փուլ 4 — Անսպասելի իրավիճակներ',
    titleEs: 'El resultado imposible',
    titleHy: 'Անհավանական հաշիվ',
    situationEs: 'Tu equipo pierde 4-0 al descanso. El entrenador os pregunta qué haréis en la segunda parte.',
    situationHy: 'Քո թիմը առաջին խաղակեսից հետո պարտվում է 4-0 հաշվով։ Մարզիչը հարցնում է՝ ինչ կանեք երկրորդ խաղակեսում։',
    questionEs: '¿Qué responderéis?',
    questionHy: 'Ի՞նչ կպատասխանեք։',
    options: [
      { key: 'A', textEs: 'Abandonaremos el estadio inmediatamente.', textHy: 'Անմիջապես կլքենք մարզադաշտը։' },
      { key: 'B', textEs: 'Seguiremos luchando hasta el final.', textHy: 'Կշարունակենք պայքարել մինչև վերջ։' },
      { key: 'C', textEs: 'Cambiaremos las reglas.', textHy: 'Կփոխենք կանոնները։' },
      { key: 'D', textEs: 'Pediremos que termine el partido ahora.', textHy: 'Կխնդրենք, որ խաղն ավարտվի հիմա։' },
    ],
    correctAnswer: 'B',
    verbInFocus: 'Seguiremos (seguir) / Responderéis (responder)',
    explanationHy: '«Seguiremos luchando hasta el final» — Իսկական թիմը երբեք չի հանձնվում և պայքարում է մինչև սուլիչի ձայնը։',
  },
  {
    id: 19,
    round: 4,
    roundTitleEs: 'Ronda 4 — Situaciones inesperadas',
    roundTitleHy: 'Փուլ 4 — Անսպասելի իրավիճակներ',
    titleEs: 'El periodista curioso',
    titleHy: 'Հետաքրքրասեր լրագրող',
    situationEs: 'Después de ganar un partido, un periodista te pregunta: «¿Qué harás con el premio?».',
    situationHy: 'Խաղում հաղթելուց հետո լրագրողը հարցնում է. «Ի՞նչ կանես մրցանակով»։',
    questionEs: '¿Qué responderás?',
    questionHy: 'Ի՞նչ կպատասխանես։',
    options: [
      { key: 'A', textEs: 'Ayer jugué muy bien.', textHy: 'Երեկ շատ լավ խաղացի։' },
      { key: 'B', textEs: 'Estoy corriendo ahora.', textHy: 'Հիմա վազում եմ։' },
      { key: 'C', textEs: 'Lo compartiré con mi equipo.', textHy: 'Կկիսեմ այն իմ թիմի հետ։' },
      { key: 'D', textEs: 'No me gustaba el estadio.', textHy: 'Ինձ դուր չէր գալիս մարզադաշտը։' },
    ],
    correctAnswer: 'C',
    verbInFocus: 'Compartiré (compartir) / Responderás (responder)',
    explanationHy: '«Lo compartiré con mi equipo» — Հաղթանակն ու մրցանակը թիմի համատեղ աշխատանքի արդյունքն են։',
  },
  {
    id: 20,
    round: 4,
    roundTitleEs: 'Ronda 4 — Situaciones inesperadas',
    roundTitleHy: 'Փուլ 4 — Անսպասելի իրավիճակներ',
    titleEs: 'La final soñada',
    titleHy: 'Երազանքի եզրափակիչը',
    situationEs: 'Mañana jugarás la final más importante de tu vida.',
    situationHy: 'Վաղը կխաղաս կյանքիդ ամենակարևոր եզրափակչում։',
    questionEs: '¿Qué harás esta noche?',
    questionHy: 'Ի՞նչ կանես այսօր երեկոյան։',
    options: [
      { key: 'A', textEs: 'Saldré de fiesta hasta las cinco.', textHy: 'Երեկույթի կգնամ մինչև ժամը հինգը։' },
      { key: 'B', textEs: 'Comeré diez hamburguesas.', textHy: 'Տասը համբուրգեր կուտեմ։' },
      { key: 'C', textEs: 'Jugaré videojuegos toda la noche.', textHy: 'Ամբողջ գիշեր տեսախաղեր կխաղամ։' },
      { key: 'D', textEs: 'Cenaré bien y me acostaré temprano.', textHy: 'Լավ կընթրեմ և շուտ կպառկեմ քնելու։' },
    ],
    correctAnswer: 'D',
    verbInFocus: 'Cenaré (cenar) / Acostaré (acostarse) / Jugarás (jugar)',
    explanationHy: '«Cenaré bien y me acostaré temprano» — Եզրափակչից առաջ առողջ սնունդն ու լիարժեք քունը վճռորոշ են։',
  },

  // Ronda 5 — Piensa rápido
  {
    id: 21,
    round: 5,
    roundTitleEs: 'Ronda 5 — Piensa rápido',
    roundTitleHy: 'Փուլ 5 — Արագ մտածիր',
    titleEs: 'El portero lesionado',
    titleHy: 'Դարպասապահի վնասվածքը',
    situationEs: 'Si el portero se lesiona durante el partido, ¿qué hará el entrenador?',
    situationHy: 'Եթե դարպասապահը վնասվածք ստանա խաղի ընթացքում, ի՞նչ կանի մարզիչը։',
    questionEs: '¿Qué opción es la correcta?',
    questionHy: 'Ո՞ր տարբերակն է ճիշտ։',
    options: [
      { key: 'A', textEs: 'Buscará un sustituto.', textHy: 'Փոխարինող կփնտրի։' },
      { key: 'B', textEs: 'Marcará cinco goles.', textHy: 'Հինգ գոլ կխփի։' },
      { key: 'C', textEs: 'Cerrará el estadio.', textHy: 'Կփակի մարզադաշտը։' },
      { key: 'D', textEs: 'Venderá el equipo.', textHy: 'Կվաճառի թիմը։' },
    ],
    correctAnswer: 'A',
    verbInFocus: 'Buscará (buscar) / Hará (hacer)',
    explanationHy: '«Buscará un sustituto» — Մարզիչը դարպասապահի փոխարինող կմտցնի դաշտ։',
  },
  {
    id: 22,
    round: 5,
    roundTitleEs: 'Ronda 5 — Piensa rápido',
    roundTitleHy: 'Փուլ 5 — Արագ մտածիր',
    titleEs: 'El calor en el campo',
    titleHy: 'Շոգը դաշտում',
    situationEs: 'Si mañana hace mucho calor durante el partido, ¿qué necesitarán los jugadores?',
    situationHy: 'Եթե վաղը խաղի ընթացքում շատ շոգ լինի, ի՞նչ պետք կգա ֆուտբոլիստներին։',
    questionEs: '¿Qué opción es la correcta?',
    questionHy: 'Ո՞ր տարբերակն է ճիշտ։',
    options: [
      { key: 'A', textEs: 'Abrigos de invierno.', textHy: 'Ձմեռային վերարկուներ։' },
      { key: 'B', textEs: 'Beberán más agua.', textHy: 'Նրանք ավելի շատ ջուր կխմեն։' },
      { key: 'C', textEs: 'Necesitarán paraguas para la nieve.', textHy: 'Անձրևանոցներ ձյան համար։' },
      { key: 'D', textEs: 'Llevarán bufandas gruesas.', textHy: 'Հաստ շարֆեր կկրեն։' },
    ],
    correctAnswer: 'B',
    verbInFocus: 'Beberán (beber) / Necesitarán (necesitar)',
    explanationHy: '«Beberán más agua» — Շոգ եղանակին ջրազրկումից խուսափելու համար ջուր խմելն անհրաժեշտ է։',
  },
  {
    id: 23,
    round: 5,
    roundTitleEs: 'Ronda 5 — Piensa rápido',
    roundTitleHy: 'Փուլ 5 — Արագ մտածիր',
    titleEs: 'La celebración del campeonato',
    titleHy: 'Առաջնության տոնակատարությունը',
    situationEs: 'Si tu equipo gana el campeonato, ¿cómo lo celebraréis?',
    situationHy: 'Եթե քո թիմը հաղթի առաջնությունում, ինչպե՞ս կնշեք հաղթանակը։',
    questionEs: '¿Qué opción es la correcta?',
    questionHy: 'Ո՞ր տարբերակն է ճիշտ։',
    options: [
      { key: 'A', textEs: 'Nos iremos a dormir sin hablar.', textHy: 'Առանց խոսելու քնելու կգնանք։' },
      { key: 'B', textEs: 'Estudiaremos química.', textHy: 'Քիմիա կսովորենք։' },
      { key: 'C', textEs: 'Levantaremos la copa y celebraremos juntos.', textHy: 'Կբարձրացնենք գավաթը և միասին կտոնենք։' },
      { key: 'D', textEs: 'Cancelaremos la victoria.', textHy: 'Կչեղարկենք հաղթանակը։' },
    ],
    correctAnswer: 'C',
    verbInFocus: 'Levantaremos (levantar) / Celebraremos (celebrar)',
    explanationHy: '«Levantaremos la copa y celebraremos juntos» — Գավաթը վեր բարձրացնելն ու միասին տոնելն ավանդույթ է։',
  },
  {
    id: 24,
    round: 5,
    roundTitleEs: 'Ronda 5 — Piensa rápido',
    roundTitleHy: 'Փուլ 5 — Արագ մտածիր',
    titleEs: 'El tiempo añadido',
    titleHy: 'Ավելացված ժամանակը',
    situationEs: 'Si el árbitro añade cinco minutos al partido, ¿qué harán los jugadores?',
    situationHy: 'Եթե մրցավարը խաղին ավելացնի հինգ րոպե, ի՞նչ կանեն ֆուտբոլիստները։',
    questionEs: '¿Qué opción es la correcta?',
    questionHy: 'Ո՞ր տարբերակն է ճիշտ։',
    options: [
      { key: 'A', textEs: 'Irán al cine.', textHy: 'Կինո կգնան։' },
      { key: 'B', textEs: 'Se cambiarán de ropa inmediatamente.', textHy: 'Անմիջապես շորերը կփոխեն։' },
      { key: 'C', textEs: 'Abandonarán todos el campo.', textHy: 'Բոլորով կլքեն խաղադաշտը։' },
      { key: 'D', textEs: 'Continuarán jugando cinco minutos más.', textHy: 'Կշարունակեն խաղալ ևս հինգ րոպե։' },
    ],
    correctAnswer: 'D',
    verbInFocus: 'Continuarán (continuar) / Añade (añadir)',
    explanationHy: '«Continuarán jugando cinco minutos más» — Խաղացողները կշարունակեն խաղը մինչև ավելացված ժամանակի ավարտը։',
  },
  {
    id: 25,
    round: 5,
    roundTitleEs: 'Ronda 5 — Piensa rápido',
    roundTitleHy: 'Փուլ 5 — Արագ մտածիր',
    titleEs: 'El nuevo entrenador',
    titleHy: 'Նոր մարզիչը',
    situationEs: 'Si mañana te conviertes en entrenador de tu equipo favorito, ¿qué será lo primero que harás?',
    situationHy: 'Եթե վաղը դառնաս քո սիրելի թիմի մարզիչը, առաջինն ի՞նչ կանես։',
    questionEs: '¿Qué opción es la correcta?',
    questionHy: 'Ո՞ր տարբերակն է ճիշտ։',
    options: [
      { key: 'A', textEs: 'Hablaré con los jugadores y prepararé un plan de entrenamiento.', textHy: 'Կխոսեմ խաղացողների հետ և մարզումների պլան կպատրաստեմ։' },
      { key: 'B', textEs: 'Cancelaré todos los entrenamientos para siempre.', textHy: 'Ընդմիշտ կչեղարկեմ բոլոր մարզումները։' },
      { key: 'C', textEs: 'Venderé todos los balones.', textHy: 'Կվաճառեմ բոլոր գնդակները։' },
      { key: 'D', textEs: 'Cambiaré el fútbol por la natación.', textHy: 'Ֆուտբոլը կփոխարինեմ լողով։' },
    ],
    correctAnswer: 'A',
    verbInFocus: 'Hablaré (hablar) / Prepararé (preparar) / Conviertes (convertirse)',
    explanationHy: '«Hablaré con los jugadores y prepararé un plan de entrenamiento» — Նոր մարզչի առաջին գործն է խոսել թիմի հետ ու պատրաստել մարզումների ծրագիր։',
  },
];

export const GAME_TWO_QUESTIONS: GameTwoQuestion[] = [
  // Ronda 1 — Calcula y responde
  {
    id: 1,
    round: 1,
    roundTitleEs: 'Ronda 1 — Calcula y responde',
    roundTitleHy: 'Փուլ 1 — Հաշվիր և պատասխանիր',
    titleEs: 'Los goles',
    titleHy: 'Գոլեր',
    contextEs: 'Un delantero marcará 3 goles el lunes, 2 el miércoles y 4 el sábado.',
    contextHy: 'Հարձակվողը երկուշաբթի կխփի 3 գոլ, չորեքշաբթի՝ 2, իսկ շաբաթ՝ 4։',
    questionEs: '¿Cuántos goles marcará en total?',
    questionHy: 'Ընդհանուր քանի՞ գոլ կխփի։',
    options: [
      { key: 'A', textEs: '7 goles', textHy: '7 գոլ' },
      { key: 'B', textEs: '8 goles', textHy: '8 գոլ' },
      { key: 'C', textEs: '9 goles', textHy: '9 գոլ' },
      { key: 'D', textEs: '10 goles', textHy: '10 գոլ' },
    ],
    correctAnswer: 'C',
    formula: '3 + 2 + 4 = 9',
    explanationEs: 'Marcará nueve goles.',
    explanationHy: 'Նա կխփի ինը գոլ։ (3 + 2 + 4 = 9)',
  },
  {
    id: 2,
    round: 1,
    roundTitleEs: 'Ronda 1 — Calcula y responde',
    roundTitleHy: 'Փուլ 1 — Հաշվիր և պատասխանիր',
    titleEs: 'El entrenamiento',
    titleHy: 'Մարզում',
    contextEs: 'Un futbolista entrenará 45 minutos por la mañana y 35 minutos por la tarde.',
    contextHy: 'Ֆուտբոլիստը առավոտյան կմարզվի 45 րոպե, իսկ երեկոյան՝ 35։',
    questionEs: '¿Cuántos minutos entrenará en total?',
    questionHy: 'Ընդհանուր քանի՞ րոպե կմարզվի։',
    options: [
      { key: 'A', textEs: '70 minutos', textHy: '70 րոպե' },
      { key: 'B', textEs: '75 minutos', textHy: '75 րոպե' },
      { key: 'C', textEs: '80 minutos', textHy: '80 րոպե' },
      { key: 'D', textEs: '90 minutos', textHy: '90 րոպե' },
    ],
    correctAnswer: 'C',
    formula: '45 + 35 = 80',
    explanationEs: 'Entrenará ochenta minutos.',
    explanationHy: 'Նա կմարզվի ութսուն րոպե։ (45 + 35 = 80 րոպե)',
  },
  {
    id: 3,
    round: 1,
    roundTitleEs: 'Ronda 1 — Calcula y responde',
    roundTitleHy: 'Փուլ 1 — Հաշվիր և պատասխանիր',
    titleEs: 'Las entradas',
    titleHy: 'Տոմսեր',
    contextEs: 'Una entrada para el partido costará 25 euros. Si cuatro amigos compran una entrada cada uno:',
    contextHy: 'Խաղի մեկ տոմսը կարժենա 25 եվրո։ Եթե չորս ընկերներից յուրաքանչյուրը մեկ տոմս գնի:',
    questionEs: '¿Cuánto pagarán?',
    questionHy: 'Որքա՞ն կվճարեն։',
    options: [
      { key: 'A', textEs: '75 €', textHy: '75 €' },
      { key: 'B', textEs: '90 €', textHy: '90 €' },
      { key: 'C', textEs: '100 €', textHy: '100 €' },
      { key: 'D', textEs: '125 €', textHy: '125 €' },
    ],
    correctAnswer: 'C',
    formula: '25 × 4 = 100',
    explanationEs: 'Pagarán cien euros.',
    explanationHy: 'Նրանք կվճարեն հարյուր եվրո։ (25 € × 4 = 100 €)',
  },
  {
    id: 4,
    round: 1,
    roundTitleEs: 'Ronda 1 — Calcula y responde',
    roundTitleHy: 'Փուլ 1 — Հաշվիր և պատասխանիր',
    titleEs: 'Los espectadores',
    titleHy: 'Հանդիսատեսներ',
    contextEs: 'En un estadio habrá 8.500 espectadores. Durante la primera parte llegarán 1.200 más.',
    contextHy: 'Մարզադաշտում կլինի 8500 հանդիսատես։ Առաջին խաղակեսի ընթացքում կգա ևս 1200 մարդ։',
    questionEs: '¿Cuántos habrá en total?',
    questionHy: 'Ընդհանուր քանի՞ հանդիսատես կլինի։',
    options: [
      { key: 'A', textEs: '9.500 espectadores', textHy: '9.500 հանդիսատես' },
      { key: 'B', textEs: '9.700 espectadores', textHy: '9.700 հանդիսատես' },
      { key: 'C', textEs: '10.200 espectadores', textHy: '10.200 հանդիսատես' },
      { key: 'D', textEs: '10.700 espectadores', textHy: '10.700 հանդիսատես' },
    ],
    correctAnswer: 'B',
    formula: '8.500 + 1.200 = 9.700',
    explanationEs: 'Habrá nueve mil setecientos espectadores.',
    explanationHy: 'Կլինի ինը հազար յոթ հարյուր հանդիսատես։ (8.500 + 1.200 = 9.700)',
  },
  {
    id: 5,
    round: 1,
    roundTitleEs: 'Ronda 1 — Calcula y responde',
    roundTitleHy: 'Փուլ 1 — Հաշվիր և պատասխանիր',
    titleEs: 'Los pases',
    titleHy: 'Փոխանցումներ',
    contextEs: 'Un centrocampista dará 28 pases en la primera parte y 36 en la segunda.',
    contextHy: 'Կիսապաշտպանը առաջին խաղակեսում կկատարի 28 փոխանցում, իսկ երկրորդում՝ 36։',
    questionEs: '¿Cuántos pases dará durante el partido?',
    questionHy: 'Ընդհանուր քանի՞ փոխանցում կկատարի։',
    options: [
      { key: 'A', textEs: '54 pases', textHy: '54 փոխանցում' },
      { key: 'B', textEs: '62 pases', textHy: '62 փոխանցում' },
      { key: 'C', textEs: '64 pases', textHy: '64 փոխանցում' },
      { key: 'D', textEs: '68 pases', textHy: '68 փոխանցում' },
    ],
    correctAnswer: 'C',
    formula: '28 + 36 = 64',
    explanationEs: 'Dará sesenta y cuatro pases.',
    explanationHy: 'Նա կկատարի վաթսունչորս փոխանցում։ (28 + 36 = 64)',
  },
  {
    id: 6,
    round: 1,
    roundTitleEs: 'Ronda 1 — Calcula y responde',
    roundTitleHy: 'Փուլ 1 — Հաշվիր և պատասխանիր',
    titleEs: 'Los puntos',
    titleHy: 'Միավորներ',
    contextEs: 'Un equipo ganará cuatro partidos y empatará dos. Si cada victoria vale tres puntos y cada empate uno:',
    contextHy: 'Թիմը կհաղթի չորս խաղում և երկու խաղ կավարտի ոչ-ոքի։ Յուրաքանչյուր հաղթանակի համար տրվում է 3 միավոր, իսկ ոչ-ոքիի համար՝ 1։',
    questionEs: '¿Cuántos puntos conseguirá?',
    questionHy: 'Քանի՞ միավոր կհավաքի։',
    options: [
      { key: 'A', textEs: '12 puntos', textHy: '12 միավոր' },
      { key: 'B', textEs: '14 puntos', textHy: '14 միավոր' },
      { key: 'C', textEs: '16 puntos', textHy: '16 միավոր' },
      { key: 'D', textEs: '18 puntos', textHy: '18 միավոր' },
    ],
    correctAnswer: 'B',
    formula: '(4 × 3) + (2 × 1) = 12 + 2 = 14',
    explanationEs: 'Conseguirá catorce puntos.',
    explanationHy: 'Թիմը կհավաքի տասնչորս միավոր։ (4 × 3 = 12 + 2 = 14)',
  },

  // Ronda 2 — ¿Qué debe saber un futbolista?
  {
    id: 7,
    round: 2,
    roundTitleEs: 'Ronda 2 — ¿Qué debe saber un futbolista?',
    roundTitleHy: 'Փուլ 2 — Ի՞նչ պետք է իմանա ֆուտբոլիստը',
    titleEs: 'La duración del partido',
    titleHy: 'Խաղի տևողությունը',
    contextEs: 'Si un partido tiene dos partes de 45 minutos:',
    contextHy: 'Եթե խաղը բաղկացած է երկու՝ 45-րոպեանոց խաղակեսից:',
    questionEs: '¿Cuántos minutos durará el tiempo reglamentario sin contar el añadido?',
    questionHy: 'Որքա՞ն կտևի հիմնական խաղաժամանակը՝ առանց ավելացված րոպեների։',
    options: [
      { key: 'A', textEs: '80 minutos', textHy: '80 րոպե' },
      { key: 'B', textEs: '85 minutos', textHy: '85 րոպե' },
      { key: 'C', textEs: '90 minutos', textHy: '90 րոպե' },
      { key: 'D', textEs: '100 minutos', textHy: '100 րոպե' },
    ],
    correctAnswer: 'C',
    formula: '45 × 2 = 90',
    explanationEs: 'Durará noventa minutos.',
    explanationHy: 'Այն կտևի իննսուն րոպե։ (45 × 2 = 90 րոպե)',
  },
  {
    id: 8,
    round: 2,
    roundTitleEs: 'Ronda 2 — ¿Qué debe saber un futbolista?',
    roundTitleHy: 'Փուլ 2 — Ի՞նչ պետք է իմանա ֆուտբոլիստը',
    titleEs: 'El calentamiento',
    titleHy: 'Նախավարժանք',
    contextEs: 'Antes de comenzar un entrenamiento intenso:',
    contextHy: 'Ինտենսիվ մարզում սկսելուց առաջ:',
    questionEs: '¿Qué hará un futbolista antes de comenzar un entrenamiento intenso?',
    questionHy: 'Ի՞նչ կանի ֆուտբոլիստը ինտենսիվ մարզում սկսելուց առաջ։',
    options: [
      { key: 'A', textEs: 'Se dormirá.', textHy: 'Քնելու կպառկի։' },
      { key: 'B', textEs: 'Hará un calentamiento.', textHy: 'Նախավարժանք կկատարի։' },
      { key: 'C', textEs: 'Comerá demasiado.', textHy: 'Շատակերությամբ կզբաղվի։' },
      { key: 'D', textEs: 'Se sentará durante una hora.', textHy: 'Մեկ ժամ կնստի։' },
    ],
    correctAnswer: 'B',
    explanationEs: 'Hará un calentamiento.',
    explanationHy: 'Նա նախավարժանք կկատարի (Hará un calentamiento)՝ վնասվածքներից խուսափելու համար։',
  },
  {
    id: 9,
    round: 2,
    roundTitleEs: 'Ronda 2 — ¿Qué debe saber un futbolista?',
    roundTitleHy: 'Փուլ 2 — Ի՞նչ պետք է իմանա ֆուտբոլիստը',
    titleEs: 'El descanso',
    titleHy: 'Հանգիստ',
    contextEs: 'Después de un partido o entrenamiento exigente:',
    contextHy: 'Խաղից կամ ծանր մարզումից հետո:',
    questionEs: '¿Por qué necesitará descansar bien un futbolista después de entrenar?',
    questionHy: 'Ինչո՞ւ ֆուտբոլիստը պետք է լավ հանգստանա մարզումից հետո։',
    options: [
      { key: 'A', textEs: 'Para olvidar las reglas.', textHy: 'Կանոնները մոռանալու համար։' },
      { key: 'B', textEs: 'Para perder su energía.', textHy: 'Էներգիան կորցնելու համար։' },
      { key: 'C', textEs: 'Para recuperarse físicamente.', textHy: 'Ֆիզիկապես վերականգնվելու համար։' },
      { key: 'D', textEs: 'Para dejar de entrenar para siempre.', textHy: 'Մարզումները ընդմիշտ թողնելու համար։' },
    ],
    correctAnswer: 'C',
    explanationEs: 'Para recuperarse físicamente.',
    explanationHy: 'Ֆիզիկապես վերականգնվելու համար (Para recuperarse físicamente)։',
  },
  {
    id: 10,
    round: 2,
    roundTitleEs: 'Ronda 2 — ¿Qué debe saber un futbolista?',
    roundTitleHy: 'Փուլ 2 — Ի՞նչ պետք է իմանա ֆուտբոլիստը',
    titleEs: 'La táctica',
    titleHy: 'Մարտավարություն',
    contextEs: 'Si un equipo juega con cuatro defensas, tres centrocampistas y tres delanteros:',
    contextHy: 'Եթե թիմը խաղում է չորս պաշտպանով, երեք կիսապաշտպանով և երեք հարձակվողով:',
    questionEs: '¿Cuántos jugadores de campo tendrá?',
    questionHy: 'Քանի՞ դաշտային ֆուտբոլիստ կունենա։',
    options: [
      { key: 'A', textEs: '9 jugadores', textHy: '9 ֆուտբոլիստ' },
      { key: 'B', textEs: '10 jugadores', textHy: '10 ֆուտբոլիստ' },
      { key: 'C', textEs: '11 jugadores', textHy: '11 ֆուտբոլիստ' },
      { key: 'D', textEs: '12 jugadores', textHy: '12 ֆուտբոլիստ' },
    ],
    correctAnswer: 'B',
    formula: '4 + 3 + 3 = 10 (jugadores de campo)',
    explanationEs: 'Tendrá diez jugadores de campo y un portero.',
    explanationHy: 'Կունենա տասը դաշտային ֆուտբոլիստ (4+3+3 = 10) և մեկ դարպասապահ (ընդամենը 11):',
  },
  {
    id: 11,
    round: 2,
    roundTitleEs: 'Ronda 2 — ¿Qué debe saber un futbolista?',
    roundTitleHy: 'Փուլ 2 — Ի՞նչ պետք է իմանա ֆուտբոլիստը',
    titleEs: 'La alimentación',
    titleHy: 'Սնունդ',
    contextEs: 'Para mantener un alto rendimiento deportivo:',
    contextHy: 'Բարձր մարզական արդյունքներ պահպանելու համար:',
    questionEs: '¿Qué deberá hacer un futbolista para tener energía durante los entrenamientos?',
    questionHy: 'Ի՞նչ պետք է անի ֆուտբոլիստը մարզումների ժամանակ էներգիա ունենալու համար։',
    options: [
      { key: 'A', textEs: 'Comer de forma equilibrada y beber suficiente agua.', textHy: 'Սնվել հավասարակշռված և բավարար ջուր խմել։' },
      { key: 'B', textEs: 'Comer solamente dulces.', textHy: 'Ուտել միայն քաղցրավենիք։' },
      { key: 'C', textEs: 'No desayunar nunca.', textHy: 'Երբեք նախաճաշ չանել։' },
      { key: 'D', textEs: 'Beber solamente refrescos.', textHy: 'Խմել միայն գազավորված ըմպելիքներ։' },
    ],
    correctAnswer: 'A',
    explanationEs: 'Comerá de forma equilibrada y beberá suficiente agua.',
    explanationHy: 'Նա հավասարակշռված կսնվի և բավարար ջուր կխմի։',
  },
  {
    id: 12,
    round: 2,
    roundTitleEs: 'Ronda 2 — ¿Qué debe saber un futbolista?',
    roundTitleHy: 'Փուլ 2 — Ի՞նչ պետք է իմանա ֆուտբոլիստը',
    titleEs: 'El trabajo en equipo',
    titleHy: 'Թիմային աշխատանք',
    contextEs: 'Durante una jugada de ataque en el partido:',
    contextHy: 'Խաղի ընթացքում հարձակողական գրոհի ժամանակ:',
    questionEs: '¿Qué hará un buen centrocampista cuando vea a un compañero en una posición mejor?',
    questionHy: 'Ի՞նչ կանի լավ կիսապաշտպանը, երբ տեսնի, որ թիմակիցն ավելի լավ դիրքում է։',
    options: [
      { key: 'A', textEs: 'Ignorará a su compañero.', textHy: 'Կանտեսի թիմակցին։' },
      { key: 'B', textEs: 'Saldrá del campo.', textHy: 'Դուրս կգա դաշտից։' },
      { key: 'C', textEs: 'Le pasará el balón.', textHy: 'Գնդակը կփոխանցի նրան։' },
      { key: 'D', textEs: 'Se sentará.', textHy: 'Կնստի։' },
    ],
    correctAnswer: 'C',
    explanationEs: 'Le pasará el balón.',
    explanationHy: 'Նա գնդակը կփոխանցի թիմակցին (Le pasará el balón)։',
  },

  // Ronda 3 — Matemáticas para un futuro campeón
  {
    id: 13,
    round: 3,
    roundTitleEs: 'Ronda 3 — Matemáticas para un futuro campeón',
    roundTitleHy: 'Փուլ 3 — Ապագա չեմպիոնի մաթեմատիկան',
    titleEs: 'Los kilómetros',
    titleHy: 'Կիլոմետրեր',
    contextEs: 'Un futbolista recorrerá 7 kilómetros en un entrenamiento y 9 en otro.',
    contextHy: 'Ֆուտբոլիստը մեկ մարզման ընթացքում կվազի 7 կմ, իսկ մյուսում՝ 9 կմ։',
    questionEs: '¿Cuántos kilómetros recorrerá en total?',
    questionHy: 'Ընդհանուր քանի՞ կիլոմետր կանցնի։',
    options: [
      { key: 'A', textEs: '14 kilómetros', textHy: '14 կմ' },
      { key: 'B', textEs: '15 kilómetros', textHy: '15 կմ' },
      { key: 'C', textEs: '16 kilómetros', textHy: '16 կմ' },
      { key: 'D', textEs: '17 kilómetros', textHy: '17 կմ' },
    ],
    correctAnswer: 'C',
    formula: '7 + 9 = 16',
    explanationEs: 'Recorrerá dieciséis kilómetros.',
    explanationHy: 'Նա կանցնի տասնվեց կիլոմետր։ (7 + 9 = 16 կմ)',
  },
  {
    id: 14,
    round: 3,
    roundTitleEs: 'Ronda 3 — Matemáticas para un futuro campeón',
    roundTitleHy: 'Փուլ 3 — Ապագա չեմպիոնի մաթեմատիկան',
    titleEs: 'El descuento',
    titleHy: 'Զեղչ',
    contextEs: 'Unas botas de fútbol cuestan 120 euros. La tienda ofrecerá un descuento de 30 euros.',
    contextHy: 'Ֆուտբոլային խաղակոշիկներն արժեն 120 եվրո։ Խանութը կտրամադրի 30 եվրո զեղչ։',
    questionEs: '¿Cuánto pagarás?',
    questionHy: 'Որքա՞ն կվճարես։',
    options: [
      { key: 'A', textEs: '80 €', textHy: '80 €' },
      { key: 'B', textEs: '90 €', textHy: '90 €' },
      { key: 'C', textEs: '100 €', textHy: '100 €' },
      { key: 'D', textEs: '110 €', textHy: '110 €' },
    ],
    correctAnswer: 'B',
    formula: '120 - 30 = 90',
    explanationEs: 'Pagaré noventa euros.',
    explanationHy: 'Ես կվճարեմ իննսուն եվրո։ (120 - 30 = 90 €)',
  },
  {
    id: 15,
    round: 3,
    roundTitleEs: 'Ronda 3 — Matemáticas para un futuro campeón',
    roundTitleHy: 'Փուլ 3 — Ապագա չեմպիոնի մաթեմատիկան',
    titleEs: 'Los penaltis',
    titleHy: 'Տասնմեկմետրանոցներ',
    contextEs: 'Un portero parará 3 penaltis de 5 lanzamientos.',
    contextHy: 'Դարպասապահը հինգ տասնմեկմետրանոցից երեքը կկասեցնի։',
    questionEs: '¿Cuántos penaltis no parará?',
    questionHy: 'Քանի՞սը չի կասեցնի։',
    options: [
      { key: 'A', textEs: '1 penalti', textHy: '1 տասնմեկմետրանոց' },
      { key: 'B', textEs: '2 penaltis', textHy: '2 տասնմեկմետրանոց' },
      { key: 'C', textEs: '3 penaltis', textHy: '3 տասնմեկմետրանոց' },
      { key: 'D', textEs: '4 penaltis', textHy: '4 տասնմեկմետրանոց' },
    ],
    correctAnswer: 'B',
    formula: '5 - 3 = 2',
    explanationEs: 'No parará dos penaltis.',
    explanationHy: 'Նա չի կասեցնի երկու տասնմեկմետրանոց։ (5 - 3 = 2)',
  },
  {
    id: 16,
    round: 3,
    roundTitleEs: 'Ronda 3 — Matemáticas para un futuro campeón',
    roundTitleHy: 'Փուլ 3 — Ապագա չեմպիոնի մաթեմատիկան',
    titleEs: 'El entrenamiento semanal',
    titleHy: 'Շաբաթական մարզում',
    contextEs: 'Un jugador entrenará 90 minutos al día durante cinco días.',
    contextHy: 'Ֆուտբոլիստը հինգ օր շարունակ օրական կմարզվի 90 րոպե։',
    questionEs: '¿Cuántas horas y minutos entrenará en total?',
    questionHy: 'Ընդհանուր քանի՞ ժամ և րոպե կմարզվի։',
    options: [
      { key: 'A', textEs: '6 horas', textHy: '6 ժամ' },
      { key: 'B', textEs: '7 horas', textHy: '7 ժամ' },
      { key: 'C', textEs: '7 horas y 30 minutos', textHy: '7 ժամ և 30 րոպե' },
      { key: 'D', textEs: '8 horas', textHy: '8 ժամ' },
    ],
    correctAnswer: 'C',
    formula: '90 × 5 = 450 min = 7 horas y 30 minutos',
    explanationEs: 'Entrenará siete horas y media.',
    explanationHy: 'Նա կմարզվի յոթ ժամ երեսուն րոպե։ (90 × 5 = 450 րոպե = 7 ժամ 30 րոպե)',
  },
];

export const COACH_QUESTIONS: CoachQuestion[] = [
  {
    id: 17,
    situationEs: 'Tu equipo pierde 2-0 al descanso.',
    situationHy: 'Քո թիմը ընդմիջմանը պարտվում է 2-0 հաշվով։',
    questionEs: '¿Qué les dirás a los jugadores?',
    questionHy: 'Ի՞նչ կասես ֆուտբոլիստներին։',
    sampleAnswerEs: 'Seguiremos luchando y trataremos de marcar dos goles.',
    sampleAnswerHy: 'Մենք կշարունակենք պայքարել և կփորձենք երկու գոլ խփել։',
    keyVerbs: ['Seguiremos (seguir)', 'Trataremos (tratar)', 'Marcar (infinitivo)'],
  },
  {
    id: 18,
    situationEs: 'Un jugador llegará tarde al entrenamiento.',
    situationHy: 'Ֆուտբոլիստը կուշանա մարզումից։',
    questionEs: '¿Qué le preguntarás?',
    questionHy: 'Ի՞նչ կհարցնես նրան։',
    sampleAnswerEs: '¿Por qué llegarás tarde? ¿Vendrás a tiempo mañana?',
    sampleAnswerHy: 'Ինչո՞ւ կուշանաս։ Վաղը ժամանակի՞ն կգաս։',
    keyVerbs: ['Llegarás (llegar)', 'Vendrás (venir: stem vendr-)'],
  },
  {
    id: 19,
    situationEs: 'Tu delantero marcará tres goles en un partido.',
    situationHy: 'Քո հարձակվողը մեկ խաղում երեք գոլ կխփի։',
    questionEs: '¿Cómo lo felicitarás?',
    questionHy: 'Ինչպե՞ս կշնորհավորես նրան։',
    sampleAnswerEs: '¡Excelente! Si sigues entrenando así, conseguirás grandes resultados.',
    sampleAnswerHy: 'Հիանալի՛ է։ Եթե շարունակես այդպես մարզվել, մեծ արդյունքների կհասնես։',
    keyVerbs: ['Conseguirás (conseguir)', 'Sigues (seguir)'],
  },
  {
    id: 20,
    situationEs: 'Mañana jugaréis contra un equipo muy fuerte.',
    situationHy: 'Վաղը կխաղաք շատ ուժեղ թիմի դեմ։',
    questionEs: '¿Qué estrategia utilizaréis?',
    questionHy: 'Ի՞նչ մարտավարություն կօգտագործեք։',
    sampleAnswerEs: 'Defenderemos bien, controlaremos el balón y aprovecharemos nuestras oportunidades.',
    sampleAnswerHy: 'Մենք լավ կպաշտպանվենք, կվերահսկենք գնդակը և կօգտվենք մեր հնարավորություններից։',
    keyVerbs: ['Defenderemos (defender)', 'Controlaremos (controlar)', 'Aprovecharemos (aprovechar)'],
  },
];

export const MENTAL_MATH_ITEMS: MentalMathItem[] = [
  {
    id: 1,
    operation: '250 + 350',
    resultNum: 600,
    spanishText: 'Seiscientos',
    armenianText: 'Վեց հարյուր',
  },
  {
    id: 2,
    operation: '1.200 + 850',
    resultNum: 2050,
    spanishText: 'Dos mil cincuenta',
    armenianText: 'Երկու հազար հիսուն',
  },
  {
    id: 3,
    operation: '3.500 − 1.250',
    resultNum: 2250,
    spanishText: 'Dos mil doscientos cincuenta',
    armenianText: 'Երկու հազար երկու հարյուր հիսուն',
  },
  {
    id: 4,
    operation: '75 × 4',
    resultNum: 300,
    spanishText: 'Trescientos',
    armenianText: 'Երեք հարյուր',
  },
  {
    id: 5,
    operation: '4.800 + 2.600',
    resultNum: 7400,
    spanishText: 'Siete mil cuatrocientos',
    armenianText: 'Յոթ հազար չորս հարյուր',
  },
  {
    id: 6,
    operation: '9.000 − 3.750',
    resultNum: 5250,
    spanishText: 'Cinco mil doscientos cincuenta',
    armenianText: 'Հինգ հազար երկու հարյուր հիսուն',
  },
];

export const FINAL_ROLE_TASKS: FinalRoleTask[] = [
  {
    role: 'Como futbolista',
    roleHy: 'Որպես ֆուտբոլիստ',
    icon: '⚽',
    promptHy: 'Ամեն օր մարզվելու մասին',
    sentenceEs: 'Como futbolista, entrenaré todos los días.',
    sentenceHy: 'Որպես ֆուտբոլիստ՝ ամեն օր կմարզվեմ։',
    verbUsed: 'entrenaré (entrenar, 1ª pers. singular)',
  },
  {
    role: 'Como entrenador',
    roleHy: 'Որպես մարզիչ',
    icon: '📋',
    promptHy: 'Թիմին օգնելու և առաջնորդելու մասին',
    sentenceEs: 'Como entrenador, ayudaré a mi equipo.',
    sentenceHy: 'Որպես մարզիչ՝ կօգնեմ իմ թիմին։',
    verbUsed: 'ayudaré (ayudar, 1ª pers. singular)',
  },
  {
    role: 'Como aficionado',
    roleHy: 'Որպես երկրպագու',
    icon: '📣',
    promptHy: 'Սիրելի ֆուտբոլիստներին աջակցելու մասին',
    sentenceEs: 'Como aficionado, apoyaré a mis jugadores favoritos.',
    sentenceHy: 'Որպես երկրպագու՝ կաջակցեմ իմ սիրելի ֆուտբոլիստներին։',
    verbUsed: 'apoyaré (apoyar, 1ª pers. singular)',
  },
];
